### ISSUE TITLE
Example usage

### ISSUE THREAD

**Issue by NicCOConnor** [lgleim/mxgraph-typings#1]
Lars, 
This looks like a great start to typings in mxGraph. it looks like there is a slight issue with the way that modules work in typescript now. when I try to use the library with `import {mxCell} from 'mxgraph'` I get the error 'No exported member' however if i remove the `export module mxgraph {}` from the index.d.ts it works as expected. 

Can you provide some example documentation on how you are utilizing the typings? 

Nic

**Comment by lgleim** [comment]
Hi Nic,
the current Mxgraph distribution is distributed as a UMD Module. Have a look at https://www.typescriptlang.org/docs/handbook/declaration-files/library-structures.html. If I follow the TypeScript recommendations, it is not possible to access the type declarations directly (which as far as I know you need in order to create typed variables). 
I will create a usage example in a moment.
Please note that these typings are generated from a partial typescript port that I worked on. I currently however do not have time to continue working on it. If you are interested I can push my WIP.
