### ISSUE TITLE
Contact: let's share efforts to implement 'mxgraph-type-definitions'

### ISSUE THREAD

**Issue by tbouffard** [lgleim/mxgraph-typings#12]
Hi @lgleim
We have recently started a [dedicated community initiative](https://github.com/process-analytics/mxgraph-road-to-DefinitelyTyped) to provide mxGraph type definitions through the [DefinitelyTyped project](https://definitelytyped.org/).

Would you agree to join?
Your repository is probably the most forked and used on GitHub, has received several external contributions so we would be pleased to get your feedbacks on mxgraph type definitions and usages.

**Comment by lgleim** [comment]
Hey Thomas,

like Rustislav, I no longer work on a project that requires mxGraph and I probably won't have the time to contribute actively. 

These typings were derived from a typescript fork of Mxgraph. Since there is currently no chance of the upstream adopting typescript, that project has been discontinued. 

Even though MxGraph is now available in Version 4, these typings still cover the large majority of functions and options. 

Feel free to use any of the type definitions in this repo and move them to the DefinitelyTyped project. 

Good luck!

**Comment by tbouffard** [comment]
Hi Lars,
thanks for having taken time to answer to my message and for providing additional information.

Bye
Thomas
