### ISSUE TITLE
How to use mxgraph in Angular CLI?

### ISSUE THREAD

**Issue by pp23** [lgleim/mxgraph-typings#3]
I have a generated a new Angular CLI project and want to use mxgraph in this project. For that, I have installed mxgraph and your typings with:

`npm install mxgraph --save`
`npm install -D lgleim/mxgraph-typings`

The mxgraph package contains a single mxClient. When I use your example code of your REAME.md file, I get the following error:

ERROR in ./src/app/graph-editor/graph-editor.component.ts
Module not found: Error: Can't resolve 'mxgraph' 

I have also tried to copy the mxgraph git repo to the directory src/mxgraph and src/assets/mxgraph, but this did not fix the error above.

Maybe you can give me some hints what I have to do to use mxgraph in an Angular CLI project with your typings?

**Comment by marvincaspar** [comment]
@pp23 could you fix this issue? I have the same

**Comment by lgleim** [comment]
Please have a look at #2. This is an issue with the upstream mxgraph project not being properly published. A workaround I have been using in the past is to install the module directly from github instead of from npm via 
```
npm install --save github:jgraph/mxgraph
```
Please feel free to file another issue at the mxgraph repository since the mxgraph developers are currently ignoring this problem.
